### ISSUE TITLE
LyZ not generating keys properly for Bib file 

### ISSUE THREAD

**Issue by Gnossos** [willsALMANJ/lyz#13] opened 2016-10-20 19:34 UTC
Using Zotero Standalone 4.0.29.15 on a Mac w/ OS X Yosemite 10.10.5 and LyZ 3.0.0 (updated June 16, 2016), I have the following reference:

Tao, Ran, and Jean-Claude Thill. 2016. “Spatial Cluster Detection in Spatial Flow Data.” Geographical Analysis 48 (4): 355–72. doi:10.1111/gean.12100.

Zotero shows the citation key as "Tao_2016_Spatial," but when I use "Cite in LyX, the item is created in the BibTeX file and the document with key "author_year_title2". However, if I use Edit > Copy Bibliography and then paste the reference in the BibTeX file opened in BibDesk, the correct citation key is used.

Cite key in LyZ is set to "author_year_title."

Installed Zotero extensions include: LyZ, MozRepl, Better BibTeX, Libre Office Integration, Scholar Citations, Word for Mac Integration, Zotero-to-BibDesk auto-import utility (Z2B), Zotero QuickLook, ZotFile, zotxt, and Zutilo. Suspect there may be some intereaction with Better BibTeX or Z2B.

Suggestions for debugging & fixing? I have log files if necessary.

**Comment by willsALMANJ** [comment] 2016-10-22 15:35
That is strange. I will look into it more when I have time. It would be helpful for me to know more about your background with LyZ. Has it worked successfully for you before or was this the first reference you tried? Does it still work successfully for other references now and just this one reference shows this behavior? Did you change anything about your setup recently (other than the Zotero and the different plugins being updated)?

For debugging, the first thing I would want to try is running Zotero with a clean profile and only LyZ installed and seeing if that reference still gets that cite key (you should be able to use a different profile by launching Zotero from the command line with the `-p` flag; the link I give in the next sentence has the command for launching Zotero from the command line). Another thing you could try is seeing if anything shows up in the debug output when you click on "Cite in LyX" using the Real-time Debug Output method here: https://www.zotero.org/support/debug_output. I think that method just gives you Zotero debug messages which might not be helpful since LyZ doesn't use them. You might get better information by replacing `-ZoteroDebug` with `-jsconsole` in those instructions which will open the Error Console. Clear the errors, click on "Cite in LyX" and see if any javascript errors show up.

Also, if the problem is limited to this one reference, try creating nominally the same reference by hand and citing that. If you had Zotero create the reference automatically, perhaps there is a special character in it that LyZ is not handling correctly.

**Comment by Gnossos** [comment] 2016-10-25 21:56
Hello,

Thank you for getting back to me. I'm sorry I could not answer you 
sooner, but I had to wait until I went into my office today. (I explain 
why below.)

I've interspersed the rest of my replies.

    Marshall Feldman
    Professor Emeritus of Labor Research and Urban Studies
    The University of Rhode Island


On 10/22/16 11:35 AM, willsALMANJ wrote:
>
> That is strange. I will look into it more when I have time. It would 
> be helpful for me to know more about your background with LyZ. Has it 
> worked successfully for you before or was this the first reference you 
> tried? Does it still work successfully for other references now and 
> just this one reference shows this behavior? Did you change anything 
> about your setup recently (other than the Zotero and the different 
> plugins being updated)?
>
I run LyZ on 3-4 different computers. AFAIK, they are identically 
configured, although updates sometimes cause their configurations to 
vary, and of course I might sometimes inadvertently do something that 
makes them different.

Right now I am using LyZ primarily on two computers, both of which are 
iMacs. One is at home, and one is in my office at work. Both use the 
Yosemite version of OS X and, AFAIK, the latest versions of Zotero, LyZ, 
and LyX. (The other two computers are a laptop, which I only use when 
traveling and another, newer iMac that's currently being stored.)

The documents I am working on, including the bib file, appear on both 
computers and are synchronized through Microsoft OneDrive. In other 
words, the identical files appear on both computers. My Zotero library 
is synchronized through Zotero's server, but I use Zotfile to store most 
of my documents on a NAS drive at home.

The problem I described with the cite keys only occurs on my "Work" 
computer, and it happens _every time I try to cite something with LyZ_.

Until the morning, my "Home" computer was doing the identical thing 
without a hitch. Then today it started running into a different problem. 
I won't bother you with this, since I hope I can fix it myself through 
some combination of restarting and reinitializing things.

> For debugging, the first thing I would want to try is running Zotero 
> with a clean profile and only LyZ installed and seeing if that 
> reference still gets that cite key (you should be able to use a 
> different profile by launching Zotero from the command line with the 
> |-p| flag; the link I give in the next sentence has the command for 
> launching Zotero from the command line). Another thing you could try 
> is seeing if anything shows up in the debug output when you click on 
> "Cite in LyX" using the Real-time Debug Output method here: 
> https://www.zotero.org/support/debug_output. I think that method just 
> gives you Zotero debug messages which might not be helpful since LyZ 
> doesn't use them. You might get better information by replacing 
> |-ZoteroDebug| with |-jsconsole| in those instructions which will open 
> the Error Console. Clear the errors, click on "Cite in LyX" and see if 
> any javascript errors show up.
>
I've never done this, and it sounds a bit complicated. I will attempt it 
when I am at work and have a few hours to devote to it. Right now I have 
a conference paper and abstract to write. So hopefully I can get to this 
either later this week or next week.
>
> Also, if the problem is limited to this one reference, try creating 
> nominally the same reference by hand and citing that. If you had 
> Zotero create the reference automatically, perhaps there is a special 
> character in it that LyZ is not handling correctly.
>
Since the problem is happening with all references, likely this is not 
the problem.

Thanks again.

**Comment by willsALMANJ** [comment] 2016-10-26 03:41
Okay, thanks for the information. I think I see what is going on. You are using the citekey `author_title_year`. However, LyZ expects this setting to be formatted with spaces between each keyword, so it should `author _ title _ year`. When LyZ creates the citekey, it removes the spaces. I will close the issue for now, but if this is not the problem we can reopen it.

**Closed by willsALMANJ** 2016-10-26 03:41 UTC

**Comment by Gnossos** [comment] 2016-10-26 17:24
OK. When I'm next in the office, I'll give this a try.

Thanks very much.

    Marsh Feldman
