### ISSUE TITLE
Compatibility with Firefox Quantum

### ISSUE THREAD

**Issue by rborder** [willsALMANJ/lyz#24] opened 2017-12-06 17:42 UTC
Are there any plans to update LyZ for the new version of Firefox? Moving forward this is likely to be the primary issue determining whether this (incredibly handy) add-on will continue to see use

**Comment by willsALMANJ** [comment] 2017-12-06 18:22
I am glad that you have found LyZ useful. Please look at issue #22 where someone else asked about this. The issue is that Zotero itself is not compatible with Firefox Quantum. LyZ is still compatible with the standalone version of Zotero. However, be aware that there appears to be a significant migration issue (#23) with moving from Zotero 4 to Zotero 5. LyZ works with Zotero 4 or Zotero 5 for new projects but the LyZ database of an existing project does not transition properly from Zotero 4 to Zotero 5.

**Comment by rborder** [comment] 2017-12-06 19:42
I see--this is helpful. Thanks for the quick response!

**Comment by willsALMANJ** [comment] 2018-01-14 13:30
Closing this now that the README has been updated.

**Closed by willsALMANJ** 2018-01-14 13:30 UTC
